############# English navigation ##############

# main menu
[[main]]
name = "Le Low-tech lab"
url = "/"
weight = 1

[[main]]
name = "La low-tech"
url = "/low-tech"
weight = 2

[[main]]
name = "Les outils"
url = "/outils"
weight = 3

[[main]]
name = "Actualités / Blog"
url = "actu-blog"
weight = 4

[[main]]
parent = "Actualités / Blog"
name = "Le wiki / les tutos"
url = "/wiki"

[[main]]
parent = "Actualités / Blog"
name = "Annuaire"
url = "/annuaire"

[[main]]
parent = "Actualités / Blog"
name = "Agenda"
url = "/agenda"

[[main]]
parent = "Actualités / Blog"
name = "Contribuer"
url = "/contribuer"


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Elements"
url = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
